src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Date_Due__c</fullName>
        <label>Date Due</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Reported__c</fullName>
        <label>Date Reported</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Equipment to be Serviced</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Maintenance_Cycle__c</fullName>
        <description>Number of days required before routine maintenance is needed</description>
        <label>Maintenance Cycle (Days)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Work_Part__c.object
<CustomObject>
    <fields>
        <fullName>Equipment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Equipment</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>No spare parts meet this description or name.</errorMessage>
            <filterItems>
                <field>Product2.Replacement_Part__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Work Parts</relationshipLabel>
        <relationshipName>Work_Parts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Maintenance_Request__c</fullName>
        <label>Maintenance Request</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Work Parts</relationshipLabel>
        <relationshipName>Work_Parts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Work Part</label>
    <nameField>
        <displayFormat>PART-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Work Parts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MaintenanceRequestHelper.cls
public class MaintenanceRequestHelper {
    
    public static void updateWorkOrders(List<Case> requests){
        List<Case> nuevos = new List<Case>();
        List<Work_Part__c> n_partes = new List<Work_Part__c>();
        for (Case c : requests) {
			Case n = new Case (Subject = 'Revisión Preventiva', Type='Routine Maintenance', 
                               Date_Reported__c =system.today(),  Origin='Web');	
            Decimal min = 0;
            
            for (Work_Part__c wp : c.Work_Parts__r) {
                if (min==0||wp.equipment__r.maintenance_cycle__c<min) {
                    min=wp.equipment__r.maintenance_cycle__c;
                }
                system.debug('Insertando WP, ID del caso = '+n.id);
             Work_Part__c nuevo_wp = New Work_Part__c (
			                 		equipment__c=wp.equipment__c,
                 					quantity__c=wp.quantity__c
             							);
          //   nuevo_wp.maintenance_request__c = c;
             n_partes.add(nuevo_wp);
            }
            c.Date_Due__c=system.today().addDays(Integer.valueof(min));
            
            
            
            nuevos.add(n);
        }
        insert nuevos;
        for (Work_part__c wp : n_partes) {
            wp.maintenance_request__c = nuevos[integer.valueof(wp.Maintenance_Request__c)].id;
        }
        insert n_partes;
    }        
    
}